// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoXTT16h2dlDiFWGLgG5mwjDr9HG_Lciw',
    appId: '1:43085288966:web:40c04d9dff24d228295587',
    messagingSenderId: '43085288966',
    projectId: 'fir-auth-697a0',
    authDomain: 'fir-auth-697a0.firebaseapp.com',
    storageBucket: 'fir-auth-697a0.firebasestorage.app',
    measurementId: 'G-GCXXW29XQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYUeKFhMpwENWjvOffe12xn1akPOxpyoI',
    appId: '1:43085288966:android:1c32645c7c64eef9295587',
    messagingSenderId: '43085288966',
    projectId: 'fir-auth-697a0',
    storageBucket: 'fir-auth-697a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1o1LnP7Q-HlJjdPYEnU04I24Mbfad7xc',
    appId: '1:43085288966:ios:01492d5022feac9b295587',
    messagingSenderId: '43085288966',
    projectId: 'fir-auth-697a0',
    storageBucket: 'fir-auth-697a0.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1o1LnP7Q-HlJjdPYEnU04I24Mbfad7xc',
    appId: '1:43085288966:ios:01492d5022feac9b295587',
    messagingSenderId: '43085288966',
    projectId: 'fir-auth-697a0',
    storageBucket: 'fir-auth-697a0.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoXTT16h2dlDiFWGLgG5mwjDr9HG_Lciw',
    appId: '1:43085288966:web:447aef34a45da733295587',
    messagingSenderId: '43085288966',
    projectId: 'fir-auth-697a0',
    authDomain: 'fir-auth-697a0.firebaseapp.com',
    storageBucket: 'fir-auth-697a0.firebasestorage.app',
    measurementId: 'G-K2PQVWZVVX',
  );
}
